update actions with push to actifactory. fix hypr-411
tiiuae/tii_sel4_build pull request #10
Opened 2022-05-27 09:05 UTC by ssrcdevops

PR for integrating ssrc artifactory with github actions. Push binaries to artifactory.

2022-05-30 06:57 UTC, elmankku requested changes
Needs a small change to make it reusable. Otherwise good.

2022-05-30 06:57 UTC, elmankku commented on .github/workflows/build-vm-images.yml
> +      - name: Preparing artifactory for upload
Please wrap the code here in a composite action, and call it here.

2022-06-01 16:42 UTC, ssrcdevops commented on .github/workflows/build-vm-images.yml
> +      - name: Preparing artifactory for upload
Acknowledged. We've added a new commit to this PR.

2022-06-03 06:53 UTC, elmankku requested changes

2022-06-03 06:53 UTC, elmankku commented on .github/actions/vm-image-publish/action.yml
> +          for DIRNAME in ${DIR[@]}; do jf rt u "$DIRNAME/images/*" tii-sel4-artifacts/; done
I think this should be a generic action for publishing artifacts - be it images, config files etc... doesn't matter. Having said that, the action should take e.g. a list of files to upload, which are given as `input`.

In addition build number mangling should be optional.

2022-06-06 06:33 UTC, amalx-ssrc commented on .github/actions/vm-image-publish/action.yml
> +          for DIRNAME in ${DIR[@]}; do jf rt u "$DIRNAME/images/*" tii-sel4-artifacts/; done
Make sense. We have included the suggestions in a new commit.

2022-06-08 08:30 UTC, elmankku requested changes

2022-06-08 08:30 UTC, elmankku commented on .github/actions/artifact-publish/action.yml
> +    required: true
How about removing this, and just checking if bd-num is empty/non-empty?

```sh
if [ -n "$BUILD_NUM" ]; then
  mv ...
fi
```

2022-06-08 08:30 UTC, elmankku commented on .github/actions/artifact-publish/action.yml
> +  bd-num:
This is a bit of nit-picking, but personally I'd prefer a longer form in an API. So `build-num` or similar.

2022-06-08 08:30 UTC, elmankku commented on .github/actions/artifact-publish/action.yml
> +  source_dir:
The naming convention changes here `foo-bar` -> `foo_bar`. The former is used in above inputs so please use that throughout the file.

2022-06-08 08:30 UTC, elmankku commented on .github/actions/artifact-publish/action.yml
> +  dest_dir:
Okay, so current approach is quite verbose to use in workflows, because it only supports one file/dir. I understand the need for destination in JFrog, so what I'm suggesting is to have _a map like lists to be passed as an input for the action_ and upload everything in a one go. 

We can introduce some constraints for the files, like
- no spaces allowed and
- no `:` symbol allowed

This can be done with one variable (input and output in the same list), or two variables (separate variables for inputs and outputs).

### Option 1

Here's an example for one variable:
```yaml
      - name: Publish images to artifactory
        uses: ./.github/actions/artifact-publish
        with:
          rt-user: ${{ secrets.rt-user }}
          rt-api-key: ${{ secrets.rt-api-key }}
          rt-url: ${{ secrets.rt-url }}
          build-num: ${{ github.run_number }}    
          input-paths:  |
            workspace/rpi4_vm_minimal/images/capdl-loader-image-arm-bcm2711:tii-sel4-artifacts/rpi4_vm_minimal/
            workspace/rpi4_vm_multi/images/capdl-loader-image-arm-bcm2711:tii-sel4-artifacts/rpi4_vm_multi/
            workspace/rpi4_sel4test/images/sel4test-driver-image-arm-bcm2711:tii-sel4-artifacts/rpi4_vm_sel4test/
            workspace/rpi4_vm_qemu_virtio/images/capdl-loader-image-arm-bcm2711:tii-sel4-artifacts/rpi4_vm_qemu_virtio/
```
And this is how it can be put to a bash associative array:

```bash
declare -A ITEMS
for input in $INPUT_PATHS; do
    ITEMS["${input%%:*}"]="${input#*:}"
done

for key in "${ITEMS[@]}"; do echo "$key => ${ITEMS[$key]}"; done
# prints
# workspace/rpi4_vm_minimal/images/capdl-loader-image-arm-bcm2711 => tii-sel4-artifacts/rpi4_vm_minimal/
# workspace/rpi4_vm_multi/images/capdl-loader-image-arm-bcm2711 => tii-sel4-artifacts/rpi4_vm_multi/
# etc etc..
```

### Option 2

And here's an example for separate variables where we use a key in both maps to identify the files. First action inputs:

```yaml
      - name: Publish images to artifactory
        uses: ./.github/actions/artifact-publish
        with:
          rt-user: ${{ secrets.rt-user }}
          rt-api-key: ${{ secrets.rt-api-key }}
          rt-url: ${{ secrets.rt-url }}
          build-num: ${{ github.run_number }}    
          input-paths:  |
            vm_minimal:workspace/rpi4_vm_minimal/images/capdl-loader-image-arm-bcm2711
            vm_multi:workspace/rpi4_vm_multi/images/capdl-loader-image-arm-bcm2711
            sel4test:workspace/rpi4_sel4test/images/sel4test-driver-image-arm-bcm2711
            vm_qemu_virtio:workspace/rpi4_vm_qemu_virtio/images/capdl-loader-image-arm-bcm2711
          output-paths: |
            vm_minimal:tii-sel4-artifacts/rpi4_vm_minimal/
            vm_multi:tii-sel4-artifacts/rpi4_vm_multi/
            sel4test:tii-sel4-artifacts/rpi4_vm_sel4test/
            vm_qemu_virtio:tii-sel4-artifacts/rpi4_vm_qemu_virtio/
```
And this is how one can create an associative array from those in bash:
```bash
declare -A ITEMS
for input in $INPUT_PATHS; do
  for output in $OUTPUT_PATHS; do
    if [ "${input%%:*}" = "${output%%:*}" ]; then
      ITEMS["${input#*:}"]="${output#*:}"
    fi
  done
done

for key in "${ITEMS[@]}"; do echo "$key => ${ITEMS[$key]}"; done
# prints
# workspace/rpi4_vm_minimal/images/capdl-loader-image-arm-bcm2711 => tii-sel4-artifacts/rpi4_vm_minimal/
# workspace/rpi4_vm_multi/images/capdl-loader-image-arm-bcm2711 => tii-sel4-artifacts/rpi4_vm_multi/
# etc etc..
```

Of course when using these, it is a good idea to validate that the inputs are in correct form before uploading anything.

2022-06-08 08:30 UTC, elmankku commented on .github/workflows/build-vm-images.yml
> +          add_bd_num: true
Uploading one file at a time gets quite verbose - see comment in `action.yml`.

2022-06-08 08:30 UTC, elmankku commented on .github/actions/artifact-publish/action.yml
> +          sudo mv $DIR $DIR-b"$BD_NUM"
Is this sudo here needed...?

2022-06-09 08:04 UTC, amalx-ssrc commented on .github/actions/artifact-publish/action.yml
> +          sudo mv $DIR $DIR-b"$BD_NUM"
Yes, sudo is required.

2022-06-09 10:37 UTC, elmankku commented on .github/actions/artifact-publish/action.yml
> +          sudo mv $DIR $DIR-b"$BD_NUM"
Okay

2022-06-13 11:18 UTC, elmankku commented
@amalx-ssrc Alright, looking good. I'll squash and make a clean commit (commit message and some trailing white spaces) and merge this.

From now in commit messages, follow [widely adopted guidelines in commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html), and keep the commit history nice and clean.

2022-06-13 11:32 UTC, elmankku commented
Alright, closing this in favor of https://github.com/tiiuae/tii_sel4_build/pull/12

2022-06-13 11:32 UTC, closed without merging