Automate build release process and render documentation
tiiuae/tii_sel4_build pull request #20
Opened 2022-08-30 07:54 UTC by amalx-ssrc

Creates a release package and uploads to artifactory.

Build release process automated using workflow_dispatch event by
collecting manifest repository location, version, release document
location during the manual trigger. Release package documentation
implemented by copying the manually edited release document from the git
repository. The build jobs for above implementations run on self hosted
github runner.

Jira: HYPR-324 & HYPR-413.

2022-09-12 07:22 UTC, elmankku requested changes
Good, getting there. A few comments.

2022-09-12 07:22 UTC, elmankku commented on .github/workflows/tii-sel4-release.yml
> +            sudo chown -R $USER.$USER ../workspace
Any particular reason for this...?

Also shoud there be `:` instead of  `.`?

2022-09-12 07:22 UTC, elmankku commented on .github/workflows/tii-sel4-release.yml
> +            sed -i '$s/$/ -c "cd vm-images;. setup.sh;bitbake vm-image-driver;exit"/' ./docker/enter_container.sh
Please create a Makefile target and additional scripts instead of modifying in place.

Modifying may have unintended side effects.

2022-09-12 07:22 UTC, elmankku commented on .github/workflows/tii-sel4-release.yml
> +        description: 'Sel4-vm release version'
Nitpick: in free text, use `seL4` (capital L) when talking about seL4 - it's the official form :)

2022-09-12 07:22 UTC, elmankku commented on .github/workflows/tii-sel4-release.yml
> +      tii_sel4_version:
Here, we have some variables using `-` and this `_`. Pick either `foo_bar` or `foo-bar`, but don't mix.

2022-09-12 07:22 UTC, elmankku commented on .github/workflows/tii-sel4-release.yml
> +      release_doc:
See previous comment about `-` vs `_`. Pick either forms.

2022-09-15 17:33 UTC, amalx-ssrc commented on .github/workflows/tii-sel4-release.yml
> +            sudo chown -R $USER.$USER ../workspace
This is for cleanup of build directory in after each build. Either of those works, we have switched to `:`.

2022-09-15 17:35 UTC, amalx-ssrc commented on .github/workflows/tii-sel4-release.yml
> +            sed -i '$s/$/ -c "cd vm-images;. setup.sh;bitbake vm-image-driver;exit"/' ./docker/enter_container.sh
We have created a new target under make file along with a new script.

2022-09-15 17:35 UTC, amalx-ssrc commented on .github/workflows/tii-sel4-release.yml
> +        description: 'Sel4-vm release version'
Sure :)

2022-09-15 17:37 UTC, amalx-ssrc commented on .github/workflows/tii-sel4-release.yml
> +      release_doc:
We have followed a uniform way now.

2022-09-16 05:54 UTC, elmankku requested changes
Just one more to go and we're good :)

2022-09-16 05:54 UTC, elmankku commented on Makefile
> +	@docker/enter_container.sh ${DIR} ${CONTAINER_COMMANDS}
Just create a separate make target, e.g.

```make
linux-image:
	@scripts/build_yocto.sh
```
`build_yocto.sh` is `build_image.sh` (latter is a bit too vague - we're building a lot of images after all). If you look at the other `scripts/build_*`, you can see that those call `enter_ container,sh` with different arguments - typically the build scripts call themselves with the arguments they were called, unless already running inside the container. This way we can enter the container without user having to care about that.

This should be enough for `build_yocto.sh`.
```sh
#!/bin/sh
set -e

# Detect whether should enter container:
#   docker     -> '/.dockerenv' file exists
#   lxc/podman -> 'container' variable is set to runtime name.
#
# With 'container' variable we support native builds too:
# export container="skip", or similar, before calling make, and entering
# container is skipped.
if [ -z "${container}" ] && [ ! -f /.dockerenv ]; then
  # shellcheck disable=SC2068
  exec docker/enter_container.sh "$(pwd)" scripts/build_yocto.sh $@
fi

cd vm-images
. setup.sh
bitbake vm-image-driver
```

2022-09-20 03:40 UTC, elmankku approved these changes

2022-09-20 05:43 UTC, merged