PR and feature verification for build
tiiuae/tii_sel4_build pull request #26
Opened 2022-12-21 09:46 UTC by amalx-ssrc

Verifying that PR opened to any of the seL4 repositories will build the seL4 artifacts without failure. Commit includes PR verification for single repository as well as multiple repositories ( when pr depends on more than
one repositories) and verifying a particular feature with branch name using manual trigger.

Jira : HYPR-365, HYPR-414 & HYPR-415

2023-01-09 09:34 UTC, elmankku requested changes

2023-01-09 09:34 UTC, elmankku commented on .github/workflows/manual.yml
> +      # repo-override: ${{ inputs.REPO_OVERRIDE }}
Remove

2023-01-09 09:34 UTC, elmankku commented on scripts/branch_override.sh
> +            capdl )
The list should be acquired from the manifest, that is if the list is needed in the first place.

I think there should't be any need for the lists here, it should just apply the overrides passed in as argument, and fail if it cannot do that. The argument should contain the repositories that are subject to override. Something that was described in HYPR-415.

2023-01-09 09:34 UTC, elmankku commented on scripts/branch_override.sh
> +curl  https://api.github.com/repos/tiiuae/${repo}/pulls?state=open -H "Accept: application/json" > api_file
The branch override should check if the branch exists, no need for PR to be open.

There are couple of reasons for this:
1. When you open a PR, and it depends on the changes to several repositories, the build is likely to fail because other repositores doesn't have PR open yet.
2. Manually triggered builds does't necessarily have any PRs open.

I think you should be able to get the branch information without cloning using `git ls-remote`.

2023-01-09 09:34 UTC, elmankku commented on scripts/branch_override.sh
> +same_repocheck () {
What does it do? Function name should imply the action it is doing. Sometimes it is good to separate the check and mutate steps.

2023-01-09 09:34 UTC, elmankku commented on scripts/branch_override.sh
> +    }
Fix indetation for the function.

2023-01-09 09:34 UTC, elmankku commented on scripts/repo_override.sh
> +REPO_OVERRIDE= $1
space

2023-01-09 09:34 UTC, elmankku commented on scripts/repo_override.sh
> +curl  https://api.github.com/repos/tiiuae/${repo}/pulls?state=open -H "Accept: application/json" > api_file
IMHO this scrip should just override one or more repositories that were passed in as an argument. It should not check if there are PRs open or not. The repo override itself should be generic and not restricted to PR only.

The workflows that need overriding, should just fill out the override variable, and this script should just apply that (given sanity checks pass).

2023-01-09 09:34 UTC, elmankku commented on scripts/repo_override.sh
> +        done
indentation.

2023-01-09 09:34 UTC, elmankku commented on .github/workflows/build-vm-images.yml
> +          ref: tii/dev-manifest
why the ref?

2023-01-10 07:43 UTC, amalx-ssrc commented on .github/workflows/manual.yml
> +      # repo-override: ${{ inputs.REPO_OVERRIDE }}
Done.

2023-01-18 11:49 UTC, closed without merging