WIP: Testing setup for the RaspberryPI
tiiuae/tii_sel4_build pull request #40
Opened 2023-03-29 11:08 UTC by jsvapiav

* add action to download and run tests
* add workflow based on those actions
* tie test workflow to run after nightly builds

JIRA: HYPR-459

2023-03-29 11:20 UTC, elmankku requested changes
Looks, good. Just couple of comments :)

2023-03-29 11:20 UTC, elmankku commented on .github/actions/download_artifacts/action.yml
> +      - name: Preparing artifactory for upload
upload -> download

2023-03-29 11:20 UTC, elmankku commented on .github/workflows/run_tests.yml
> +          build-name: 'NIGHTLYBUILD'
How about workflow input with default value

2023-03-29 11:41 UTC, jsvapiav commented on .github/workflows/run_tests.yml
> +          build-name: 'NIGHTLYBUILD'
sorry, I did not get which default value do you mean?

2023-03-29 11:41 UTC, jsvapiav commented on .github/actions/download_artifacts/action.yml
> +      - name: Preparing artifactory for upload
oh, yeah. thanks=)

2023-03-30 07:11 UTC, jsvapiav commented on .github/workflows/run_tests.yml
> +          build-name: 'NIGHTLYBUILD'
Did you mean put `NIGHTLYBUILD` as default to 'build-name'?

2023-03-30 07:17 UTC, elmankku commented on .github/workflows/run_tests.yml
> +          build-name: 'NIGHTLYBUILD'
Meaning the workflow should declare input, it can be optional with some sensible default value (like something from the environment). The build-name input should be passed to the workflow by a calling workflow. Inputs can be defined to workflows just like to actions.

2023-04-27 11:07 UTC, closed without merging